### ISSUE TITLE
Companion:  Check firmware compatibility gives me 2 error messages

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2448]
An observation, maybe not a bug.

Last weekend I flew with 2.1.
Today, the first thing I did was update the firmware to today's daily (was very pleased to see  the language Nederlands added).

I then loaded the models from my radio into companion.
I noticed that the receivers on all models were turned off in companion (maybe this is normal?).

I saved my settings on the radio to be able to revert to this situation and I wrote all the settings to the radio to see if my radio would have the receiver set to off.

Companion came with this error:
![schermafdruk 2015-07-10 07 52 24](https://cloud.githubusercontent.com/assets/8692856/8612953/8ac719f8-26d9-11e5-8491-fcda04014526.png)
![schermafdruk 2015-07-10 08 07 07](https://cloud.githubusercontent.com/assets/8692856/8613065/be53826a-26da-11e5-8a62-1afd3e02abea.png)

I checked the radio afterwards and the receiver settings were still in the radio.

Then I repeated the procedure. (the radio has the settings that were loaded with today's companion).
The same thing happened....

I don't get these error messages if I turn off "Check Firmware Compatibity"
Can you tell me if it's normal that radio settings don't appear in Companion 2.1?

![schermafdruk 2015-07-10 08 15 48](https://cloud.githubusercontent.com/assets/8692856/8613165/f831998a-26db-11e5-98e1-31d4b2c47ba8.png)

EEPROM
![eeprom-2015-07-10-07-36-50](https://cloud.githubusercontent.com/assets/8692856/8613121/7d69de88-26db-11e5-9813-2a7cc07c96be.jpg)

**Comment by fraternl** [comment]
The settings in my radio did get compromised after this procedure. The "Check FW compatibity" prevented the writing to the radio, I now realize.
I can now continue to turn the radio on for all models and repeat the procedure.....

Maybe all this is normal because there was an eeprom change.

Should I check more than just radio settings?

**Comment by kilrah** [comment]
> noticed that the receivers on all models were turned off in companion (maybe this is normal?)

No it's issue #2425.

**Comment by fraternl** [comment]
I went back to 2.0.17 loaded my last 2.0.17 and went through the complete upgrade procedure.
That's issue is solved.

It did give me a chance to do the whole procedure again.
This time I filled all telemetry parameters using Companion....

In the process I discovered a little bug for which I will now create a ticket  :-)

**Comment by kilrah** [comment]
So is there still a problem with the check compatibility feature?

**Comment by fraternl** [comment]
I have definitely upgraded to today's ROM
Companion 2.1 still give me a warning if I write the settings to the radio with the option "Check FW Compatibilty"
