### ISSUE TITLE
Output jitter - visable on mixer screen and RX output

### ISSUE THREAD

**Issue by ChrisParish** [opentx/opentx#2774]
I am experiencing quite a lot of jitter on the outputs from the RX. On closer inspection the gitter is visible on the channels and mixer output screen as a bluring of the last digit. This is the case even on channels which are sourced from a switch if that switch is then applied through a curve.

I use various high channels as mix channels and when they are applied to the RX output channels via curves I then get the jitter. I would speculate that the problem is related to the output from the curves.

Running 2.1 on X9E and 2.1.1 on X9D and both are the same. Down-grading the X9D to 2.0.X removes the problem. 

Although the jitter is only slight it manifests itself in digital servos in the form of buzzing and chatter which was not present in previous versions of the firmware. Measured using a logic analyser the output gitters by around 1~2 microseconds.

**Comment by kilrah** [comment]
Strange... Please upload your settings file to a file sharing site and post the link here!

**Comment by ChrisParish** [comment]
Here you go:
https://www.dropbox.com/s/9gnuzfe9pk7bqn7/gitter.eepe?dl=0

**Comment by kilrah** [comment]
Thanks, can you also tell us what particular channel to look at?

**Comment by ChrisParish** [comment]
The jitter is usually evedent on channels 1 to 6 and 32. Channel 1 is has a switch as the input and uses a curve for shaping the output so I would expect to see no jitter on this as the input is either -100 or 100

**Comment by ChrisParish** [comment]
I have created a quick video to illustrate the problem:

https://youtu.be/YjDNc9IfK5w

**Comment by kilrah** [comment]
There was definitely something wrong with CH1 and I think I got it. The others are normal analog jitter from what I can see.

**Comment by ChrisParish** [comment]
What is strange is that the jitter is much worse with the 2.1+ firmware. Going back to the 2.0.X on the X9D fixes the jitter. Obvously I cannot do that with the X9E.
The other channels which are giving me greif are also not sourced directly from a stick, but via another channel. 
It appears that the greater pecentage of the channels input that comes from a mix channel or non-stick source then the worse it is.

**Comment by kilrah** [comment]
Can you try this?
http://www.andrebernet.ch/divers/opentx/opentx_issue2774.zip

**Comment by ChrisParish** [comment]
That just drove my TX a)french and b) mad.
Did you compile for X9E?

**Comment by kilrah** [comment]
Ah sorry, that was for an X9D+, didn't notice you only had a non-Plus.
Wait for the review of #2775 and try the nightlies if merged then.

**Comment by jjmouris** [comment]
Hi all, i am the one with a X9D+ but the above zip file now seems to no longer be there. For the moment i have gone back to 2.0.17 as this issue is very noticable on my airframes and i don't want to wear out the brushes faster on the very expensive servo motors (Hitec 7115). Have to say, the rest of 2.1.1 looks very nice indeed. 

For reference, the issue was first reported here by me.
http://www.rcgroups.com/forums/showpost.php?p=32514006&postcount=817

**Comment by ChrisParish** [comment]
I have the file if you want to try it. 

Ps. Fight over who first reported it?? Really?

;)

C

**Comment by kilrah** [comment]
File is back in place

**Comment by jjmouris** [comment]
No fight, was just to link in the thread. :)

**Comment by ChrisParish** [comment]
If I deselect the trim option from all mixer which are sourced from a non-stick source then the problem goes away. Looks like you are onto something.

**Comment by fraternl** [comment]
So that's why I never noticed that.
Not really a user error, but these shouldn't be enabled...
I hope it will now get a fix soon

**Comment by kilrah** [comment]
Should be fixed in next nightly.

**Comment by jjmouris** [comment]
So what is the status of this problem? I see the thread is closed? But this issue is still alive for me untill it is incorperated in V2.1.2 or what?

**Comment by kilrah** [comment]
The fix has been coded and merged into the master branch, which means next release (2.1.2) will include it.

**Comment by jjmouris** [comment]
Any idea when 2.1.2 will be released?

**Comment by kilrah** [comment]
Very shortly.
