### ISSUE TITLE
servo offset of 6.6 stored as 6.5 (companion and radio?)

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3156]
When setting in companion the servo offset to a value of 6.6, it is stored as 6.5.
You can change it thorugh the radio setup screen, which will adjust the underlying value.

Use this script to test, Set servo offset on channel 0 to 6.6 and go to the telemetry screen to check values.

This must/is related to the PREC1 PREC2 issue #3150, since the model.drawNumber function with PREC1 does improper roundoff, also demonstrated in the attached script.

Replacing the offset value by 66 as hardcoded integer value produce the same erroneous result

Code to be run as telemetry script:

local function run()
  lcd.clear()
  local x=10
  local y=1
  
  lcd.drawText(x+40,y,"drawNumber ch1 offset")    
  lcd.drawNumber(x,y,model.getOutput(0)["offset"],LEFT)
    
  y=y+10
  lcd.drawText(x+40,y,"drawNumber (ch1 offset/10)")
  lcd.drawNumber(x,y,model.getOutput(0)["offset"]/10,LEFT)
  
  y=y+10
  lcd.drawText(x+40,y,"drawText (ch1 offset/10)")
  lcd.drawText(x,y,model.getOutput(0)["offset"]/10)
  
  y=y+10
  lcd.drawText(x+40,y,"drawNum(ch1 offset/10) PREC1")
  lcd.drawNumber(x,y,model.getOutput(0)["offset"]/10,PREC1+LEFT)
  
  y=y+10
  lcd.drawText(x+40,y,"drawNumber (66 / 10) PREC1")
  lcd.drawNumber(x,y,66/10,PREC1+LEFT)
   
  y=y+10
  lcd.drawText(x+40,y,"drawTEXT (66 / 10)")
  lcd.drawText(x,y,66/10)
end

return {run=run}

**Comment by kilrah** [comment]
I believe it's unrelated, and you're rather seeing the 1000/1024 ratio that exists between setting and servo output.

**Comment by lshems** [comment]
Nop, i've checked the 1000/1024 ratio, and for outputs, which are noted as -100% - 100% the model.getinput() will return the % value * 10, and not the % value * 10.24.

See screenshots:
![2015-12-16](https://cloud.githubusercontent.com/assets/12395806/11841081/f20006d6-a3fa-11e5-985a-648cd4995709.png)
![2015-12-16 1](https://cloud.githubusercontent.com/assets/12395806/11841084/f89a9394-a3fa-11e5-8a87-6de0800429df.png)

**Comment by lshems** [comment]
I think the culprit is in the way you have ordered things. If you first multiple the argument with the prec factor(10 or 100) and then do the conversion to integer and then proceed in processing the result with the decimal formatting flag, all is fine.

**Comment by projectkk2glider** [comment]
It is a problem with drawNumber and PREC which was already fixed in  #3150. Please test with nightly  build #575 or later.

**Comment by lshems** [comment]
Thanks :)

Steep learning curve here.

LOL

**Comment by lshems** [comment]
Tested, unfortunately, the companion still doesn't save some values correct. 6.6 is saved as 6.5.

The simulator works correct and stores correct.

**Comment by projectkk2glider** [comment]
The remaining problem/solution is probably the same as https://github.com/opentx/opentx/issues/3117#issuecomment-163155722

**Comment by lshems** [comment]
Agree. Not blocking for me, but not pretty either.

Is it on the radio as we'll?
Op 18-dec.-2015 10:07 schreef "Damjan Adamic" <notifications@github.com>
het volgende:

**Comment by projectkk2glider** [comment]
>When setting in companion the servo offset to a value of 6.6, it is stored as 6.5.

Similar problem to #3117, which I can not reproduce (again :angry:) Anyway there is a fix done, @lshems please test next the nightly build and report back.
