### ISSUE TITLE
Audio missing in Mac version of Companion

### ISSUE THREAD

**Issue by rmcclurg** [opentx/opentx#3438]

**Comment by rmcclurg** [comment]
I checked the following versions of Companion 2.0.17, 2.0.19, 2.1.7, and 2.1.8. The only version of Companion that plays audio from Special Functions is 2.0.17. This problem was fixed some time ago by including the correct audio libraries in the Mac compile. It appears that at some point after 2.0.17 the compilation for Macs changed and left out the needed libraries.

**Comment by projectkk2glider** [comment]
@bsongis this is most likely the result of your MAC build VM.

**Comment by bsongis** [comment]
If I am not mistaken I should recompile Qt with Phonon support on the MAC VM. I think it will wait OpenTX 2.2 Companion (Qt5 based) where Phonon is replaced by QtMultimedia and is included in the original packages.

**Comment by schwabe** [comment]
Is all sound missing or only play tracks? (E.g. do the trim sounds work)

**Comment by rmcclurg** [comment]
Just checked 2.1,8 and trim beeps and "trim center" play fine. The model name plays as well. Looks like it is just play track.

**Comment by schwabe** [comment]
I cannot reproduce this. Can you double check that your sd card path is set under the radio profile and the audio tracks you are trying to play are really there?

**Comment by projectkk2glider** [comment]
There are two different audio subsystems used in Companion:
 * for listening to the selected track (blue triangle button) in Special function dialog a **Phonon** library (or **QtMultimedia** in 2.2) is used
 * for Simulator a **SDL Audio** library is used

So depending on which library is available the sound could work in both places, only one or none.

**Comment by schwabe** [comment]
@projectkk2glider Ah I see now. Yes that blue triangle thing is broken for me as well. The OpenTX 2.2 Companion just works out of the box.

**Comment by projectkk2glider** [comment]
@schwabe is this still a problem? I hope not and this can be closed.

**Comment by kilrah** [comment]
Should be fixed by #4212

**Comment by schwabe** [comment]
I think 2.1.x builds still have the problem but I don't want to spend time to fix the cmake package script for 2.1
