### ISSUE TITLE
Q7 Battery Graph not correct

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#4277]
Small display issue on the Q7 batter graph.

Essentially despite the  voltage range being correct - and the battery fully charged (checked with multimeter) the graph never shows the graph as 'full'.

I suspect the issue is that the voltage is not reading the calibrated voltage value - but rather the raw and incorrect voltage.

**Comment by 3djc** [comment]
Please give data : what voltage you measured, what was displayed, what is you range

**Comment by robthomson** [comment]
Lipo: 2 cell
Graph: 3 lines (about 25%)
Displayed voltage:  7.7v
Voltage Range: 6.6-8.5

**Comment by 3djc** [comment]
Not sure I understand, you said full charged bat, but surely this is not the case at 7.7 ?

**Comment by robthomson** [comment]
No.. its not currently charged.  But 7.7 is not 25%.

Closer to 57% if my maths is right?

**Comment by kilrah** [comment]
The charge of a lipo is not linear - the meter however is because it's not tuned to any particular type. 
It's only intended as a very rough estimation.
Also - Your lipo won't ever reach 8.5V, but the battery meter will only show full there as that's what you've configured. Typically if you want the graph to be useful you set the end points to a bit LESS than your battery's actual range, e.g. 6.8-8.2

**Comment by robthomson** [comment]
Ok.. let me clarify further.

The pack is on 7.7 now.

But the bar graph still only showed 3 bars even when it was a fresh pack at 8.2!

**Comment by projectkk2glider** [comment]
Your math is right `100×(7,7−6,6)÷(8,5−6,6) = 57%`

I also tested on simulator, looks ok:
![snapshot_01](https://cloud.githubusercontent.com/assets/5950438/22248674/171a2878-e240-11e6-917b-979619805b96.png)
![snapshot_02](https://cloud.githubusercontent.com/assets/5950438/22248678/1965119c-e240-11e6-80fd-9afb15d8b944.png)

What is displayed voltage in your case?

**Comment by projectkk2glider** [comment]
Perhaps it was fixed already, which version of OpenTX are you using?

**Comment by robthomson** [comment]
Again...  let me show you more values.

 changed mine to a LiFe

Pack is on 6.6v
Range: 6.2v->7v

Graph still shows only 3 bars.

Running: 2.2.0N360 on the x7d

Rob

**Comment by robthomson** [comment]
If I change the range to 6.2 -> 6.6v

I get 5 bars.  50%

**Comment by projectkk2glider** [comment]
>Pack is on 6.6v

Is this measured or displayed voltage?

**Comment by robthomson** [comment]
Measured and Displayed

I think the issue is that the voltage for the graph is maybe coming from the non calibrated value?

My radio read this value as higher when I plugged a meter on the battery with the radio running.

So I reduced it to match the meter in the calibration/setup screens.

**Comment by projectkk2glider** [comment]
Ok, fund fbe11119b8e7257c49b61ac1f72acecf32a150cd which fixed this, which is probbably after the N360

**Comment by 3djc** [comment]
Yes N360 was Dec 4th, this is 11th

**Comment by projectkk2glider** [comment]
Jep, N360 was 3. December. Case closed

**Comment by robthomson** [comment]
Hmm..    I downloaded and installed this firmware from companion a matter of a week ago! 

Must work out why it is an old version!

**Comment by 3djc** [comment]
I believe x7 are factory delivered with a firmware dated Dec 22nd,  wich is newer than what you can currently get from companion updates. That will change when we release n361

**Comment by robthomson** [comment]
OK.    Makes sense.   My re-flash to get multi module support downgraded me :)
