### ISSUE TITLE
Companion 2.2.0 telemetry 'switches' not available in custom functions

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#5019]
On the radio, you can setup special function based on a sensor been true or not

You cannot do that on companion, and if you import a radio with such a special function, the line stay empty

![image](https://user-images.githubusercontent.com/5167938/26962601-946286d8-4ce7-11e7-9eea-dff755ecf4ac.png)

And yes, we do have a little issue on the screen, I'll deal with that ;)

**Comment by mpaperno** [comment]
Also the `Telem[etry streaming]` "switch" is missing, right?  We don't even have enums for either of those, so it's no wonder they're missing in the lists. :)

Are there any screens/contexts besides the Special Functions where sensor "switches" should be shown?  (They're already shown in `RawSource` selectors in some cases.)

```cpp
  enum SwitchContext
  {
    LogicalSwitchesContext,
    SpecialFunctionsContext,
    GlobalFunctionsContext,
    TimersContext,
    MixesContext
  };
```


> ... based on a sensor been true or not

Meaning `true` if the sensor value != 0, or based on sensor being present/active?

**Comment by kilrah** [comment]
> Also the Telem[etry streaming] "switch" is missing, right? 

Nope this one is there

![screenshot_x7_17-06-09_08-22-16](https://user-images.githubusercontent.com/6065069/26963421-c6ca2c5c-4cec-11e7-8b78-e6194f9a16f3.png)

**Comment by mpaperno** [comment]
I meant in Companion.

**Comment by kilrah** [comment]
Ooh yes... too early :\

**Comment by tavdog** [comment]
This issue seems it should be an easy fix but I can't find anywhere in the source where all the options are listed.

**Comment by kilrah** [comment]
That was fixed long ago.

**Comment by tavdog** [comment]
This bug is still present in companion 2.2.  When setting up Telem switch in the transmitter, then opening the config in companion, the Telem switch goes to --.

--edit. nevermind.  It is fixed in the nightly builds, but hasn't made it to the official release yet.
