### ISSUE TITLE
[Companion] Naming convention in Sync tool

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#6490]
As discussed in this PR #6465 there is some inconsistency about the naming convention.

Same thing must be done for the branch 2.2. 😄

**Comment by notlebowski** [comment]
For what it's worth I agree that "source" and "destination" are open to interpretation.
The last time I used it my "best guess" was wrong.
local/remote would be fine. But other names could be fine too.

**Comment by LapinFou** [comment]
Are you sure this has been fixed?
I didn't see any modification during my latest French translation.

**Comment by svefro** [comment]
not fixed on windows english as of version 2.3.10 option says local and remote but sync direction still says destination and source.
