### ISSUE TITLE
X9Lite otx 2.30N49  Modell generating with wizzard  Error at Input Name Ias IGas

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#6581]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by hrenz** [comment]
Testing X9Lite with different Languages German, France, Englich, Czech,.....
otx 2.30 N49
Modell generating with wizzard

English is ok, Input Name is correct
but at France, and German the Input Name is one Character too left 
so its  Eas  insteed of EGas    or    Ias insteed  IGas

![2019-07-20_151845](https://user-images.githubusercontent.com/6217896/61579572-1cee2280-ab07-11e9-8000-9d83a8830956.jpg)

**Comment by kilrah** [comment]
SD card up to date with 2.3 contents?

**Comment by hrenz** [comment]
its a SD-Card V2.3.0 V0019 Version, original Tx from Frsky /Engel
All test were made with same SD-card, so its the same wizzard for the languages
en, ge, fr, cz

other users have same issues with german,  Input  one character too left
I am surpriced too because this was ok since  V2.10 
so it must be at openTx V2.3.0 German ?  
![2019-07-20_165306](https://user-images.githubusercontent.com/6217896/61580209-7c503080-ab0f-11e9-8f07-efa83b24dcbd.jpg)

**Comment by 3djc** [comment]
I cannot seem to reproduce
![image](https://user-images.githubusercontent.com/5167938/61589459-562b9e80-abaa-11e9-8a1e-0e0713e5fb74.png)

**Comment by 3djc** [comment]
This is linked to the wizard process, models created with Otx default are fine

I cannot reproduce for french firmware, but german definitively has this issue

**Comment by hrenz** [comment]
Ah, ok  at the German version 
And there is an error with spezialchar  äöü too  
allways H8h insteed of Höh  for  Elevator

**Comment by kilrah** [comment]
Companion does not support reading/writing special chars to the radio. If you don't want that you can change the wizard translations to set "Hoh" instead of "Höh".

**Comment by hrenz** [comment]
ok, where is the wizard translation

**Comment by kilrah** [comment]
In the companion translations.

One question, you did not say if you did those in the companion wizard or with the radio wizard, which on is it?.

**Comment by hrenz** [comment]
Hallo Andre,
X9Lite otx 2.30N49 Modell generating with wizzard Error at Input Name Ias IGas (#6581)

About the 2 pictures you see at #6581,I did it all with otx germanand  wizzard direct, not from companion 

----------------------------------------------------------------------------I have Companion not tested in this detailbecause in Companion you see Inputname: HohInputsource: Höh
at Mixersource: Hoh, 
But the Simulator in companion is allways in english, and I have not transferd from companion to tx
I think with the cmake file, we can set language-paramter  to de and the companion Simulator will come in german too.This will help all other users very much for SimulatorThis Funktion is missing since yearsBecause Horus X10, X12 has no screenshot funktion, and the screenshot Picture in companion Simulator is english thats not good for writing manulas in cz,  pl,  rus
mfgH. Renz
-----Ursprüngliche Mitteilung-----
Von: Andre Bernet <notifications@github.com>
An: opentx/opentx <opentx@noreply.github.com>
Cc: hrenz <hrenz62961@aol.com>; Author <author@noreply.github.com>
Verschickt: Mo, 22. Jul. 2019 13:24
Betreff: Re: [opentx/opentx] X9Lite otx 2.30N49 Modell generating with wizzard Error at Input Name Ias IGas (#6581)

In the companion translations.One question, you did not say if you did those in the companion wizard or with the radio wizard, which on is it?.—

**Comment by bsongis** [comment]
This issue is fixed now, it will be OK in next nightly build

**Comment by hrenz** [comment]
Hallo Bertrand,
openTx v2.3.N68  X9-Lite (small display)

sorry, problem is not solved, look at screenshots
Wrong positinons of the name IGas IH8h, ISei, IQue
 and H8h insteed of Höh  (Elevator)

 mfgH.Renz

 
-----Ursprüngliche Mitteilung-----
Von: Bertrand Songis <notifications@github.com>
An: opentx/opentx <opentx@noreply.github.com>
Cc: hrenz <hrenz62961@aol.com>; Author <author@noreply.github.com>
Verschickt: Mo, 22. Jul. 2019 21:09
Betreff: Re: [opentx/opentx] X9Lite otx 2.30N49 Modell generating with wizzard Error at Input Name Ias IGas (#6581)

This issue is fixed now, it will be OK in next nightly build—

**Comment by bsongis** [comment]
I just tested, I see no issue anymore, unless I didn't understand what you did.

![snapshot_01](https://user-images.githubusercontent.com/5603504/63832775-cda2d980-c971-11e9-928e-d18f4529dab2.png)
![snapshot_02](https://user-images.githubusercontent.com/5603504/63832781-d0053380-c971-11e9-8abd-a2e7fb1c14df.png)
![snapshot_03](https://user-images.githubusercontent.com/5603504/63832786-d2678d80-c971-11e9-81c1-a9c1f8c58bd6.png)
![snapshot_04](https://user-images.githubusercontent.com/5603504/63832794-d72c4180-c971-11e9-986c-e4ddedad5017.png)
