### ISSUE TITLE
X9D 2.3N062 wrong LS conversion

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6631]
Radio converts telemetry value (Distance) in logic switches (V1) into Input 17.
Companion converts correctly.

![LS](https://user-images.githubusercontent.com/23188713/63085738-7f8fde00-bf4e-11e9-8c3b-9a88d64b6862.jpg)

**Comment by raphaelcoeffic** [comment]
What do you mean by “convert”? Was it an existing model you converted from 2.2.x firmware? It would be nice to be more explicit with the steps necessary to reproduce.

**Comment by Allerhopp** [comment]
Yes

**Comment by raphaelcoeffic** [comment]
@Allerhopp I've tested manually (+added automated test) and it seems that the issue is not with the radio, where it just works fine, but with companion itself. Once the model is loaded into companion, the source is not displayed.

This is what I entered in Companion 2.2.4:
<img width="617" alt="Screen Shot 2019-08-21 at 07 59 44" src="https://user-images.githubusercontent.com/1050031/63406283-b603a800-c3e9-11e9-98d4-a038469d23ed.png">

And here is how it looks like with current 2.3 code:
<img width="608" alt="Screen Shot 2019-08-21 at 07 59 10" src="https://user-images.githubusercontent.com/1050031/63406301-c3b92d80-c3e9-11e9-9e98-89bec15b6bc2.png">

On the simu with 2.3 X9D+, it looks just fine:
<img width="249" alt="Screen Shot 2019-08-21 at 08 01 49" src="https://user-images.githubusercontent.com/1050031/63406390-067b0580-c3ea-11e9-907b-90a783f99dbb.png">

**Comment by notlebowski** [comment]
I am using delta as well to give me an altitude callout each 20 metres and noticed that wasn't working anymore. I reconstructed that part of my setup.

**Comment by notlebowski** [comment]
Is it possible that this is already fixed in 2.3N67?
I just read a model which uses a delta together with Altitude and it reads this correctly.

**Comment by raphaelcoeffic** [comment]
@notlebowski nope, if you open a 2.2 model in 2.3 companion, the bug is still there. Should be fixed shortly though, I'm on it.

**Comment by notlebowski** [comment]
Both radio and companion are on 2.3 in my setup nowadays.
I am not sure when this conversion error happened.
Maybe I read a setup once after my radio was brought back to 2.2 because I had other conversion errors.
I can't read 2.2 otx files with Companion 2.3 at this moment.
This means I can't use the "compare tool" to verify my models.

At the moment I'm only reading setups in Companion from my radio and do all the editing on the radio as I'm afraid to introduce some errors due to Companion.

This doesn't mean Companion is doing anything wrong now (I'm running nightly N67 and don't build from source anymore).
