### ISSUE TITLE
[2.3.0 RC1 and RC2] RSSI- stays at zero

### ISSUE THREAD

**Issue by 0crap** [opentx/opentx#6745]
I installed OpenTX 2.3.0 RC1 on my Taranis QX7S.
I noticed that the RSSI- value always stays at zero. (See picture.)

On nightly build 2.3.0N63 this was working correctly.

**Comment by 0crap** [comment]
![screen-2019-09-11-212152](https://user-images.githubusercontent.com/31951195/64728798-1f07a880-d4dc-11e9-9894-d965660f0e92.jpg)

**Comment by notlebowski** [comment]
That's RSSI-
The lowest value detected....
Still....  not very useful.

I never used it.
Did it always give sane values on 2.2.4???

**Comment by 0crap** [comment]
I know what RSSI- is.
It gives you the lowest value of RSSI seen in the entire flight.
On the bench next to the TX it should give something like 87 as in the example above.
It's now stuck at zero, always. (e.g. not working)

Yes, it gives sane values in 2.2.2 which I used for a long time.
Also worked fine in 2.3.0N63, from that I jumped on RC1 which gives the issue.

**Comment by 3djc** [comment]
Technicaly it is not wrong at all, but agreed not very usefull if RSSI- always reports 0

**Comment by 0crap** [comment]
@3djc Not sure why you say it's technically not wrong, because I think it is wrong.
But anyway, thanks for fixing the issue!
I'll retest when RC2 comes out.

**Comment by 3djc** [comment]
Because rssi- means the lowest received value, which is 0. But we also recognise that this is not an helpful value, so we agreed to make an exception for this sensor, where rssi- will contain the lowest non zero value

**Comment by 0crap** [comment]
@3djc It's still not clear to me why this behaviour is changed in RC1.

So with the lowest received value is 0 you mean the TX is turned ON but the craft is still OFF, not connected to a lipo?
In that case yes, the TX receives nothing and RSSI and RSSI- is zero.

But that is not how it worked in the past!
RSSI- always started to do it's thing after I plugged in a lipo. (Strong and so high RSSI- value because close to TX when plugging in.)

I think RSSI- should only start to do something when there is first a valid RSSI signal received.
Which is the case when the craft is connected to a lipo.

Usually I fly more then one pack and the TX stays ON in between pack changes.
It's always been the case that I was able to see an RSSI- value of the last flight.
Mostly around 43 or something if I fly far away. If I see that in my goggles it's time to turn around.

**Comment by bsongis** [comment]
It was a bug which has been fixed today. Will be in RC2

**Comment by 0crap** [comment]
@bsongis or @3djc Can you please reopen this issue? I just tested RC2 and the problem is still there.

![screen-2019-09-13-214613](https://user-images.githubusercontent.com/31951195/64891177-8c990d80-d671-11e9-926a-9c8a2b8b4aa3.jpg)

I also tested with Curr- , that gives the same problem, always zero.
Tested that by arming my quad and let the motors spin at low rpm.
Then reset telemetry by using my tTu (trim Throttle up) switch which I have configured to reset telem.
When tTu is active you see all the values zero out as expected.
When you release the switch, motors still armed, you expect Curr- and RSSI- to give the same values as the actual Curr and RSSI are reading.
This does not happen as you can see in the screenshot.

I would not be suprised if all telemetry [sensor]- readings are stuck at zero.
However for now I only tested Curr- and RSSI-

**Comment by 3djc** [comment]
We fixed it and it seems indeed tro have reappeared

**Comment by 0crap** [comment]
Thx, let me know if you want more sensors tested.

**Comment by 0crap** [comment]
Tested and fix confirmed.
Thx gents!
Closing this one.
