### ISSUE TITLE
2.3RC1 X9D+ SE 2019 ACCESS RX + R9M LBT (not ACCESS) Problem

### ISSUE THREAD

**Issue by uragano47812** [opentx/opentx#6760]
I have 2.3RC1 on my taranis SE 2019 i installed for the first time the R9M (not 2019 ACCESS version).
I have a signal critical allarm when using the R9 mini rx and a 2.4ghz rx even in ACCESS or in D16.
If i goes to Range test i see that the value goes from a number to 0 very quick.

If i disable internal module i see that the alarm is still there and i have 0 on RSSI on R9M.

I notice that the problem goes away if i bind the R9mini with telemetry on.

But this will be an issue using it with redundancy.

I have all the modules and rx updated to latest firmware version.

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by 3djc** [comment]
Since absolutely no details describing the actual issue are given, closing until more detail are provided

**Comment by uragano47812** [comment]
i had a problem with editor and i was re-taping the text sorry

**Comment by 3djc** [comment]
No problem

**Comment by 3djc** [comment]
I do not understand, «  i have 0 on RSSI on R9M « and «  the problem goes away if i bind the R9mini with telemetry on.«  seem to be contradictory, as it suggests you are running with telem off on r9, so how can you have r9m rssi ?

**Comment by uragano47812** [comment]
I try to describe better, if i use both module and both rx with telemetry on all is working and i don't have any allarm.

If i use R9mini rx without telemetry (for redundancy for example) i have the message signal critical. If i go to range test on both internal module and ecternal module buttons i read a number (ex 78) and 0 and so on and the radio gives the alarm.

Also if leave enabled only R9M i have RSSI 0 in range test without telemetry but also the radio gives the alarm.

But as i understand i can't leave even the new ACCESS telemetry work with R9mini in redundancy with telemtry on.

**Comment by bsongis** [comment]
Someone helps to explain to me this issue?

**Comment by uragano47812** [comment]
to summarize i think that it is not normal that the TX say signal critical if i use R9M and R9mini with telemetry off

**Comment by 3djc** [comment]
Side comment, you now should be able to have both your telem on with 2.3 and a combination of access and accst. There is also a new item, RSSI Source that let you choose which of your RSSI should be used for the top bar and so on

**Comment by bsongis** [comment]
Now I understand, it should be fixed in RC2, please confirm, thanks in advance

**Comment by 3djc** [comment]
@uragano47812 we think this is solved in N87 or RC2 when it becomes available

**Comment by kilrah** [comment]
Would be nice if you could confirm it's working in N87 before we release RC2.

**Comment by uragano47812** [comment]
I tested with N87 and the problem is still there. I get signal critical alarm when i'm using both module int + ext ind one of them is bound with the rx without telemetry. I get also on RSSI quick switch from 0 to 78 (example) and signal critical alarm.

I don't have signal critical alarm only when both RX have telemetry ON or both RX have telemetry OFF.

**Comment by 3djc** [comment]
Not related to this issue, but could you try settings up the dual telem using RSSI source ? It should work fine, you should be able to keep both telem on (this is a 2.3 change)

**Comment by bsongis** [comment]
@uragano47812 are you able to check the fix within one hour or so (before we release the RC2)?

**Comment by uragano47812** [comment]
now i can but i don't any new N88 vers. just re download N87 for the fix?

**Comment by kilrah** [comment]
RC2 is out now, should work there

**Comment by uragano47812** [comment]
Yes it works i confirm. Great job thanks.
