### ISSUE TITLE
Horus-like radios have communication problems with multiprotocol module.

### ISSUE THREAD

**Issue by prikrylm** [opentx/opentx#8653]
**Describe the bug**
I turned off both TX modules. If I want to start the external MPM, the LED flashes ("Slow blink(on=0.5s,off=0.5s): serial has been selected but no valid signal is being seen on the RX pin.").
If I start the external module with the internal module turned on, the MPM will start normally and work well, even if I turn off the internal module. If I switch the external module again (the internal module is switched off), the communication problem starts again. 

Problem start since OTX v2.3.13 (maybe v2.3.12?) Horus X12S with ISRM module as well as RadioMaster TX16S. V2.3.11 works well. There is no problem with otx 2.3.14 on Taranis (pre2019) radio.

**General information**
 - OpenTX version 2.3.13, 2.3.14
 - tested on RadioMaster TX16S and FrSky Horus X12S with ISRM

**Comment by kilrah** [comment]
Could be that your module needs a bootloader update, there was something that was fixed in it for a similar issue quite a while ago.

**Comment by prikrylm** [comment]
Bootloader in the module is from [Flash-multi v0.6.1](https://github.com/benlye/flash-multi/releases/tag/0.6.1), so there is probably no newer one.

**Comment by Skelly1001** [comment]
I have the HORUS X10s (not express model or upgraded transmitter module) and have the same problem.  I upgraded the boot loader to 0.6.1 and that didn't fix it.  In order to set up the MPM, I have to turn on the internal module, then turn on the external module, set the protocol I want to use and then turn off the internal module.  Until I do this steps, I'm left with the flashing red lights and a "invalid protocol" message.  After setting up the MPM for a plane, the previously established MPM setup works on subsequent sessions without going through this procedure.  Thanks to prikryllm for the post above.  I would haven't figured it out without his tip.  We definitely have a bug here.

**Comment by 3djc** [comment]
Issue confirmed, investigation in progress

**Comment by RadekKaplan** [comment]
Hello, today I investigated this ...

on my Horus X12S working OpenTX 2.3.10 fine, but 2.3.14 not ... I try many tryes for solution of this situation ... and this is my result :

if I use OpenTX with EXTERNALACCESSMOD option, then MultiModule not comunicated ... 
if I use OpenTX without EXTERNALACCESSMOD option, then all working fine 
( I use latest version 2.3.14 only with option LUA )

I think : implementation of support for External Acces Module is not working correct ... maybe

**Comment by 3djc** [comment]
Do you have two radios to test ? Because external access mod requires radio hardware mods

**Comment by RadekKaplan** [comment]
No, I just think a lot of users will check the EXTERNALACCESSMOD option (just like me) and don't even know what they chose

And the result is - broken communication with MultiModule

**Comment by RadekKaplan** [comment]
I have 2 pcs of Horus X12S with iXJS, but they have no HW modification. I just downloaded the firmware I thought it would allow me to work with the red R9 ACCESS module.

**Comment by 3djc** [comment]
That’s perfectly normal, no external module will work if you try to use external access mod version on a non modded radio, the same way a modded radio will not run a regular otx version

**Comment by RadekKaplan** [comment]
I just wanted to help. I think that a similar mistake as I could have been made by many other users who did not know what version of FW they were downloading.
Just a classic - I'll check as many boxes as possible

Have a nice evening !
