### ISSUE TITLE
Companion: t-pro switches missing

### ISSUE THREAD

**Issue by arkarkark** [opentx/opentx#8839]
**Describe the bug**

I'm unable to select SW1 or SA for special functions or anything really
also in the simulator the switches are missing. To be fair the factory firmware shipped with the T-pro doesn't seem to support the switches properly either.

**To Reproduce**
1. edit a model on a t-pro radio
2. go to special functions
3. try and play a track when switch 1 is either on, off or in the middle position 
4. There is no way to select switch 1 or switch a whatever you want to call it

also in the simulator the switches and momentary buttons are missing.

![image](https://user-images.githubusercontent.com/877895/150636711-20843b06-07f2-40d2-8a5e-e828a78eb2de.png)

or if you copy over a model from a t-lite that has something set to play a track for each of the three positions for switch A then it doesn't import correctly and the switch selectors are blank

![image](https://user-images.githubusercontent.com/877895/150636642-70ee9a5e-5a76-466b-8052-99fed1ccf207.png)

**Expected behavior**

I should be able to make a track play for each of the three positions on the buttons and for each momentary trigger button and also for the 6 buttons above the display.

**Screenshots**

**General information**
 - OpenTX version N631
 - Hardware T-Pro
 - OpenTX Companion OSX

**Comment by 3djc** [comment]
Import and other improvement are part of N632
Function switches firmware side has been improved too, please get latest nightly

**Comment by karmensarodjo** [comment]
hi 3djc,

i'm using 2.3.15N632 Jan.22 2022 right now, and the simulator switches are still missing, and the 6 little buttons are still disable...

**Comment by 3djc** [comment]
Yes, that's why it is still opened

**Comment by arkarkark** [comment]
confirmed this is fixed in N633 Thanks so much!

**Comment by 3djc** [comment]
What is fixed and what isn't, because the 6switch on simu arent working, right ?

**Comment by 3djc** [comment]
I think those are still opened

![image](https://user-images.githubusercontent.com/5167938/150670567-7bfcd95f-789d-4baa-9e54-94e62e58b21a.png)

![image](https://user-images.githubusercontent.com/877895/150636642-70ee9a5e-5a76-466b-8052-99fed1ccf207.png)

On the later, SA works, but SW1-6 are missing

**Comment by arkarkark** [comment]
SA -> SD switch options are there in Companion.

Indeed, the 6 momentary switches are still not there. good call leaving this open. Sorry.
